name: "Podcast Generator"
author: "Nuryn Insyirah"
description: "Generates a feed for a podcast from a YAML file."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "podcast"
  color: "pink"
inputs:
  email:
    decription: The commiter's email address
    required: true
    default: ${{github.actor }}@localhost
  name:
    descriotion: The commiter's name
    required: true
    default: ${{github.actor }}